#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
# Querying Nginx at its root (/) with a GET request (requesting a page)
#    curl http://54.196.37.117/   --> returns string "Hello World!"
#   curl http://54.196.37.117/   --> returns header info

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

#testing nginx configuration
sudo nginx -t

sudo service nginx reload
